# fly.toml app configuration file generated for chess-websocket on 2023-11-22T08:41:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chess-websocket"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
